### ISSUE TITLE
found some typos

### ISSUE THREAD

**Issue by tyziasentykk** [QuaternionMark/Homestuck-Quirk-Generator#29]
1. cirava, konyyl, galekh, charun, and marvus are missing
2. stelsa lamati???
3. vriska, equius, feferi, kankri, porrim, aranea, horuss, skylla, bronya, tagora, vikare, zebruh, remele, azdaja, tegiri, marsti, fozzer, nihkee, and lanque should all have autocaps
4. mallek should end every line with ;
5. polypa should replace commas with *, and chixie replaces commas with /
6. meulin should have the prefix
7. latula's emoticon should be >8]
8. tirona's emoticon should be 33:)

**Comment by QuaternionMark** [comment]
1. Added Cirava and Marvus. The other trolls mentioned either have no quirk or no elegant way of adding their's to the site.
2. They're already on the site.
3. If by autocaps you mean adding proper capitalization to sentences, then that's not a feature I would want to add to the site.
4. Mallek only replaces periods with semicolons as far as I can tell and not end of lines.
5. Added.
6. Meulin apparently has 10+ prefixes for different emotions, which isn't feasible to add.
7. Added.
8. Can't confirm this but added nonetheless.

**Comment by QuaternionMark** [comment]
Whoops. Fixed.
