### ISSUE TITLE
Marvus's quirk is only making it all lowercase, and Kanaya's quirk isn't excluding punctuation?

### ISSUE THREAD

**Issue by terminallyStupid** [QuaternionMark/Homestuck-Quirk-Generator#32]
sorry if I'm doing this wrong, idk what I'm doing

**Comment by QuaternionMark** [comment]
Marvus should be fixed now. When creating the Friendsim quirks I just used the wiki as a guide, but so far it's been wrong on multiple occasions after looking up footage of the game. Let me know if you find other inconsistencies!

I'm not sure what you mean by Kanaya's quirk not excluding punctuation. Can you show what text you are using?
![image](https://user-images.githubusercontent.com/21148093/125175428-003ad180-e19a-11eb-845b-b3300b4683e6.png)

**Comment by skylarvlalonde** [comment]
Oh, I think they mean that Kanaya's quirk should remove punctuation from the input text, since she doesn't use any. I drew something up to fix that and made a pull request.

**Comment by QuaternionMark** [comment]
> since she doesn't use any

[That doesn't appear to be the case](https://www.homestuck.com/story/6059), but they do remove contraction marks from contractions so that needs to be updated.

**Comment by QuaternionMark** [comment]
Going to close this issue, see [this comment](https://github.com/QuaternionMark/Homestuck-Quirk-Generator/pull/33#issuecomment-883845740) for details.
